version: 2

project_name: essay

before:
  hooks:
    - go mod tidy

builds:
  - binary: essay
    main: .
    ldflags:
      - -s -w
      - -X essay.sh/cli/cmd.GitHubClientID={{ .Env.ESSAY_GITHUB_CLIENT_ID }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: timmywheels
    name: essay
